# Infocepts Hackathon Submission
#### Sahaj Porwal

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

xml = minidom.parse('infocept_xml_data_.xml')
print('parse complete')
rows = xml.getElementsByTagName('row')
lists = []
for i in range(24):
    lists.append([])
print(lists)

Due to memory restraints on my end, have to process xml as text file

In [2]:
lines = open('infocept_xml_data_.xml').readlines()
for i in range(len(lines)):
    lines[i] = lines[i].replace(' ','')
    lines[i] = lines[i].replace('\n','')
lines[:30]

["<?xmlversion='1.0'encoding='utf-8'?>",
 '<data>',
 '<row>',
 '<index>0</index>',
 '<user_session>8b69208e-7c64-422d-b670-5b9d82d25606</user_session>',
 '<total_clicks>7</total_clicks>',
 '<total_items>2</total_items>',
 '<total_cats>1</total_cats>',
 '<max_dwell>0.5115078598666931</max_dwell>',
 '<mean_dwell>5.995877926032465</mean_dwell>',
 '<total_duration>166.71117484170466</total_duration>',
 '<click_rate>0.0725244742626448</click_rate>',
 '<day_of_week>1</day_of_week>',
 '<is_weekend>0</is_weekend>',
 '<is_special_day>0</is_special_day>',
 '<time_of_day>2</time_of_day>',
 '<cat_most_viewed_n_times>2.0</cat_most_viewed_n_times>',
 '<cat_most_viewed>2053013560982667520</cat_most_viewed>',
 '<prod_most_viewed_n_times>1.0</prod_most_viewed_n_times>',
 '<prod_most_viewed>1030297</prod_most_viewed>',
 '<cat_views_freqs>0.2678021521567366</cat_views_freqs>',
 '<prod_views_freqs>0.0009451491729694</prod_views_freqs>',
 '<cat_buys_freqs>0.2337402332570538</cat_buys_freqs>',
 '<prod_buys_freqs>0.0006900279353354</prod_buys_freqs>',
 '<is_purchase>0</is_purchase>',
 '<start_time_ts>October07,2019Monday,00:08:28</start_time_ts>',
 '<end_time_ts>October26,2019Saturday,16:08:29</end_time_ts>',
 '</row>',
 '<row>',
 '<index>1</index>']

In [3]:
lines = lines[2:-1]

In [4]:
lines[0]

'<row>'

In [5]:
lines[-1]

'</row>'

In [6]:
lists = {'index':[],
         'user_session':[],
         'total_clicks':[],
         'total_items':[],
         'total_cats':[],
    'max_dwell':[],
    'mean_dwell':[],
    'total_duration':[],
    'click_rate':[],
    'day_of_week':[],
    'is_weekend':[],
    'is_special_day':[],
    'time_of_day':[],
    'cat_most_viewed_n_times':[],
    'cat_most_viewed':[],
    'prod_most_viewed_n_times':[],
    'prod_most_viewed':[],
    'cat_views_freqs':[],
    'prod_views_freqs':[],
    'cat_buys_freqs':[],
    'prod_buys_freqs':[],
    'is_purchase':[],
    'start_time_ts':[],
    'end_time_ts':[],
    'row':[],
    '/row':[],
        }

In [7]:
for i in range(len(lines)):
    if(np.mod(i-1,1000000)==0):
        print('line',i-1,'/',len(lines),' processed')
    line = lines[i]
    #print(line)
    prop = line[(line.find('<')+1):line.find('>')]
    value = line[(line.find('>')+1):(line.find('</'))]
    #print('prop:',prop,',value:',value)
    lists[prop].append(value)

line 0 / 13000000  processed
line 1000000 / 13000000  processed
line 2000000 / 13000000  processed
line 3000000 / 13000000  processed
line 4000000 / 13000000  processed
line 5000000 / 13000000  processed
line 6000000 / 13000000  processed
line 7000000 / 13000000  processed
line 8000000 / 13000000  processed
line 9000000 / 13000000  processed
line 10000000 / 13000000  processed
line 11000000 / 13000000  processed
line 12000000 / 13000000  processed

In [8]:
for k in lists.keys():
    print(k,':',len(lists[k]))

index : 500000
user_session : 500000
total_clicks : 500000
total_items : 500000
total_cats : 500000
max_dwell : 500000
mean_dwell : 500000
total_duration : 500000
click_rate : 500000
day_of_week : 500000
is_weekend : 500000
is_special_day : 500000
time_of_day : 500000
cat_most_viewed_n_times : 500000
cat_most_viewed : 500000
prod_most_viewed_n_times : 500000
prod_most_viewed : 500000
cat_views_freqs : 500000
prod_views_freqs : 500000
cat_buys_freqs : 500000
prod_buys_freqs : 500000
is_purchase : 500000
start_time_ts : 500000
end_time_ts : 500000
row : 500000
/row : 500000

In [9]:
df = pd.DataFrame(lists)

In [10]:
df.isnull().sum()

index                       0
user_session                0
total_clicks                0
total_items                 0
total_cats                  0
max_dwell                   0
mean_dwell                  0
total_duration              0
click_rate                  0
day_of_week                 0
is_weekend                  0
is_special_day              0
time_of_day                 0
cat_most_viewed_n_times     0
cat_most_viewed             0
prod_most_viewed_n_times    0
prod_most_viewed            0
cat_views_freqs             0
prod_views_freqs            0
cat_buys_freqs              0
prod_buys_freqs             0
is_purchase                 0
start_time_ts               0
end_time_ts                 0
row                         0
/row                        0
dtype: int64

In [11]:
df.describe()

,index,user_session,total_clicks,total_items,total_cats,max_dwell,mean_dwell,total_duration,click_rate,day_of_week,...,prod_most_viewed,cat_views_freqs,prod_views_freqs,cat_buys_freqs,prod_buys_freqs,is_purchase,start_time_ts,end_time_ts,row,/row
count,500000,500000,500000,500000,500000,500000,500000,500000,500000,500000,...,500000,500000,500000,500000,500000,500000,500000,500000,500000,500000
unique,500000,4554,108,30,12,499079,499433,499392,497696,7,...,258705,439890,497164,458859,498248,2,9639,9964,1,1
top,0,7f4552c6-bd51-4953-96cd-406c3c415c78,3,2,1,0.0265153619729528,0.4473481536775847,0.0179044662510351,2.33402186978492e-05,5,...,58389345,1.5328373284689834e-06,0.0009452780904926,0.4550292185895114,0.0022251079786619,0,"October01,2019Tuesday,02:29:49","October13,2019Sunday,14:34:50",,
freq,1,1013,88783,247639,425140,121,3,121,170,260104,...,701,38401,4,20478,10,400000,1769,172,500000,500000

In [12]:
df = df.drop(['row','/row'],axis = 1)

In [13]:
df.describe()

,index,user_session,total_clicks,total_items,total_cats,max_dwell,mean_dwell,total_duration,click_rate,day_of_week,...,cat_most_viewed,prod_most_viewed_n_times,prod_most_viewed,cat_views_freqs,prod_views_freqs,cat_buys_freqs,prod_buys_freqs,is_purchase,start_time_ts,end_time_ts
count,500000,500000,500000,500000,500000,500000,500000,500000,500000,500000,...,500000,500000,500000,500000,500000,500000,500000,500000,500000,500000
unique,500000,4554,108,30,12,499079,499433,499392,497696,7,...,497965,23,258705,439890,497164,458859,498248,2,9639,9964
top,0,7f4552c6-bd51-4953-96cd-406c3c415c78,3,2,1,0.0265153619729528,0.4473481536775847,0.0179044662510351,2.33402186978492e-05,5,...,2053013561292255744,1.0,58389345,1.5328373284689834e-06,0.0009452780904926,0.4550292185895114,0.0022251079786619,0,"October01,2019Tuesday,02:29:49","October13,2019Sunday,14:34:50"
freq,1,1013,88783,247639,425140,121,3,121,170,260104,...,3,191717,701,38401,4,20478,10,400000,1769,172

In [14]:
df.columns

Index(['index', 'user_session', 'total_clicks', 'total_items', 'total_cats',
       'max_dwell', 'mean_dwell', 'total_duration', 'click_rate',
       'day_of_week', 'is_weekend', 'is_special_day', 'time_of_day',
       'cat_most_viewed_n_times', 'cat_most_viewed',
       'prod_most_viewed_n_times', 'prod_most_viewed', 'cat_views_freqs',
       'prod_views_freqs', 'cat_buys_freqs', 'prod_buys_freqs', 'is_purchase',
       'start_time_ts', 'end_time_ts'],
      dtype='object')

In [15]:
sub_df = pd.DataFrame()

In [16]:
time_spec_points = []
for time in df['start_time_ts']:
    time = time.split(',')
    time = int(time[-1].split(':')[0])
    if(time>=16):
        time+=5
    time_spec_points.append(time)
sub_df['time_spec_points'] = time_spec_points

In [17]:
total_duration = np.round(df['total_duration'].apply(lambda x: float(x)),2)
df['total_duration'] = total_duration

In [18]:
give_big_discount = np.logical_and(np.logical_not(df.day_of_week),df.is_special_day)
sub_df['give_big_discount'] = give_big_discount

In [19]:
sub_df['prod_views_buys_ratio'] = df.prod_views_freqs.apply(lambda x: float(x))/df.prod_buys_freqs.apply(lambda x: float(x))

In [20]:
df['total_clicks']=df['total_clicks'].apply(lambda x: int(x))
df['total_items']=df['total_items'].apply(lambda x: int(x))
df['total_cats']  =df['total_cats'].apply(lambda x: int(x))

In [21]:
total_inv = df['total_clicks']+df['total_items']+df['total_cats']

In [22]:
for i in range(len(total_inv)):
    if(total_inv[i]>10):
        total_inv[i]*=2

In [23]:
total_inv.shape

(500000,)

In [24]:
sub_df['total_inventory'] = total_inv

In [33]:
l_points = []
for i in range(0,len(df)):
    if(np.mod(i-1,10000)==0):
        print('Processed: ',i-1)
    if(total_duration[i]>3 & int(df['day_of_week'][i])==7):
        l_points.append(10*(int(df['day_of_week'])-3))
    else:
        l_points.append(0)
sub_df['loyalty_points'] = l_points

Processed:  0
Processed:  10000
Processed:  20000
Processed:  30000
Processed:  40000
Processed:  50000
Processed:  60000
Processed:  70000
Processed:  80000
Processed:  90000
Processed:  100000
Processed:  110000
Processed:  120000
Processed:  130000
Processed:  140000
Processed:  150000
Processed:  160000
Processed:  170000
Processed:  180000
Processed:  190000
Processed:  200000
Processed:  210000
Processed:  220000
Processed:  230000
Processed:  240000
Processed:  250000
Processed:  260000
Processed:  270000
Processed:  280000
Processed:  290000
Processed:  300000
Processed:  310000
Processed:  320000
Processed:  330000
Processed:  340000
Processed:  350000
Processed:  360000
Processed:  370000
Processed:  380000
Processed:  390000
Processed:  400000
Processed:  410000
Processed:  420000
Processed:  430000
Processed:  440000
Processed:  450000
Processed:  460000
Processed:  470000
Processed:  480000
Processed:  490000

In [31]:
submission_sample = pd.read_csv('infocept_submission.csv')

In [32]:
sub_cols = submission_sample.columns

In [34]:
for col in sub_cols:
    if(col not in sub_df.columns):
        sub_df[col] = df[col]

In [35]:
sub_df

,time_spec_points,give_big_discount,prod_views_buys_ratio,total_inventory,loyalty_points,total_duration,is_special_day,prod_views_freqs,prod_buys_freqs
0,0,False,1.369726,10,0,166.71,0,0.0009451491729694,0.0006900279353354
1,15,False,1.371440,10,0,0.43,0,0.0009458164456021,0.0006896519366427
2,26,False,1.369958,50,0,0.94,0,0.0009453910736723,0.0006900877869533
3,26,False,1.279051,5,0,0.42,0,0.0009449909696147,0.0007388217985755
4,13,False,1.370596,7,0,2.49,0,0.0009450520425059,0.0006895188328313
...,...,...,...,...,...,...,...,...,...
499995,21,False,1.371798,10,0,0.22,0,0.0009454431480033,0.0006891999811895
499996,6,False,1.368774,5,0,6.56,0,0.0009453124484181,0.0006906272505139
499997,9,False,1.393979,10,0,0.02,0,0.000962097369776,0.0006901807946017
499998,23,False,1.370726,7,0,0.02,0,0.0009455540189927,0.0006898196227254
499999,3,False,1.393921,6,0,0.02,0,0.0009616425010724,0.0006898828855845

In [36]:
sub_df.to_csv('my_submission_file.csv',index = False)